apiVersion: v1
kind: secret
metadata:
  name: ca-key-pair
  namespace: cert-manager
data:
  tls.crt: Cg==
  tls.key: Cg==
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-Issuer
  namespace: cert-manager
spec:
  ca:
    secretName: ca-key-pair
  