apiVersion: v1
kind: Secret
metadata:
  name: memberlist
type: Opaque
data:
  secretkey: NFhMTTRvOCtZSGh0N0JObzlwd1JJL1dlVUNGb2hmMkNwQ3BSOFhucHhveVlMMjMwNjRnbkFUL1NpOGVjU0J0Mwp1WHJkTDFOU1RTcWZIUmhnNUpDWlJSeDNacXRwWjJKcElzWjdUaTVwVjBBUWUySDZRN2NXd3VsQUljR0EwVUJjCjdhaFlqVTI2OTRYMTRRcVBaMTcveTBuVWJrSjJ4N1FuNFBMM0lvYzZEd1U9
