ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesCRD:
    enabled: true

logs:
  general:
    level: INFO

ports:
  #web:
  #  redirectTo: websecure
  websecure:
    tls:
      enabled: true
      domains:
        - main: edge.fcos-k8s-single.genesis.workoutperf.com
          sans: 
            - *.edge.fcos-k8s-single.genesis.workoutperf.com
            - edge.fcos-k8s-single
            - *.edge.fcos-k8s-single

service:
  spec:
    loadBalancerIP: "192.168.1.60"